### ISSUE TITLE
I am unable to add it in my application using CLI.

### ISSUE THREAD

**Issue by UsamaIslam** [Wikitude/wikitude-cordova-plugin#124]

**Comment by danielguttenberg** [comment]
Good morning,

you are correct. Currently there is an issue with installing the 7.0.0 release from GitHub. An explanation and the workaround can be found [here](https://github.com/Wikitude/wikitude-cordova-plugin/issues/122#issuecomment-315492948) and [here](https://github.com/Wikitude/wikitude-cordova-plugin/issues/121#event-1166996819).

Daniel

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @UsamaIslam,
We released a solution to the problem just a few moments ago. Please let me know if you still encounter the problem with the latest changes.

**Comment by TheCell** [comment]
Hey there I tried those workarounds but this did not help. I am using windows and I'm preparing the ios version aswell on windows, copy it to a mac machine and run it then. But after the 7.0 SDK I am unable to prepare the ios Version. Even if I clone the git locally and add the wikitude via local path the same problem persists. 

I guess my Problem is that there was only an .sh script

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @TheCell,
Are you using PhoneGap or Ionic to create your application? Which command(s) do you use to add the Wikitude Cordova plugin to your project?

Best regards,
Andreas

**Comment by TheCell** [comment]
Hey @AndreasFoetschlWikitude I use PhoneGap and I tried the `cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git` also I tried it with `cordova plugin add (localpath)`

**Comment by supreetpal** [comment]
I am trying to add this using cli to a basic cordova app and failing.

`cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git`

fails to fetch and leads to the following error:

```
Error: Failed to fetch plugin https://github.com/Wikitude/wikitude-cordova-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @supreetpal,
Based on the log output it seems that your git binary is not accessible. Can you describe you PC setup in more detail?

Best regards,
Andreas

**Comment by supreetpal** [comment]
It works fine if I use version 6.

I am using it inside a vagrant setup.

```
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "wikitude-ar"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.vm.network "public_network", ip: "192.168.20.200", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 35729, host: 35729
  config.vm.synced_folder ".", "/wikitude-ar", type: "nfs"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.ssh.forward_agent = true
end
```

**Comment by AndreasSchacherbauerWikitude** [comment]
Version 7 of our SDK has a file larger than 100 MB, so git-lfs is required.
Are you building a Cordova based application?

**Comment by supreetpal** [comment]
It worked fine after I installed git-lfs. Yes, I am building a cordova based application. Maybe the requirement for git-lfs should be mentioned more clearly in the docs. Thanks for the help.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @TheCell,
I releases a new version of the install script yesterday. Could you please try to install the Wikitude Cordova plugin from the `additional_script_logging` feature branch?

Best regards,
Andreas

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @supreetpal,
Yes, you are right. We will add some more documentation in our next release. The GitHub file size limit caused an unexpected big problem and we're still gathering issue reports from our customers to solve all of them.

Best regards,
Andreas

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @all,
We just merged the changes from the last days into master. The new merge script should handle multiple installs correctly. 
Please let us know if you still encounter issues with the new version!

Best regards,
Andreas

**Comment by prateekchitransh1907** [comment]
E:\ionicar\WikitudeIonic3StarterApp>ionic cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git --nofetch
> cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git --save
Error: Failed to fetch plugin https://github.com/Wikitude/wikitude-cordova-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/Wikitude/wikitude-cordova-plugin.git resetting remote C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50: Cloning into bare repository 'C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50'...
npm ERR! git clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50: fatal: early EOF
npm ERR! git clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50: fatal: The remote end hung up unexpectedly
npm ERR! git clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50: fatal: index-pack failed
npm ERR! git clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50: error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Wikitude/wikitude-cordova-plugin.git" "--production" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/Wikitude/wikitude-cordova-plugin.git C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50
npm ERR! Cloning into bare repository 'C:\Users\PR327171\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Wikitude-wikitude-cordova-plugin-git-e8ff2c50'...
npm ERR! fatal: early EOF
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: index-pack failed
npm ERR! error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\ionicar\WikitudeIonic3StarterApp\npm-debug.log
[ERROR] An error occurred while running cordova plugin add https://github.com/Wikitude/wikitude-cordova-plugin.git
        --sav... (exit code 1).


Still facing this issue in ionic 3.
